### PR TITLE
updated for qtc 3.4

### PR DESCRIPTION
**Pull request by dwieland**
Seems like some headers changed and Utils::FileName can't be converted to QString anymore.

### CODE REVIEW

**Comment by OneMoreGres** [comment]
I'll check request when qtc is officially released. Api can change still.

**Comment by delaitre** [comment]
Not directly related to this PR, but do you plan to have this plugin (and your other ones) upstreamed (i.e. integrated into QtCreator source code directly)?
I guess this one might be rejected because of the new Qt Test pane integration in the commercial Qt Creator though.

**Comment by OneMoreGres** [comment]
Source updated. Thanks for patch.

**Comment by OneMoreGres** [comment]
About distribution. Most of plugins are experimental and others should be modified/refactored, before i'll be able to say that they are stable. So for now, i don't plan to add plugins to QtCreator's main distribution. But who knows :)

**Pull request closed without merging**
